[project]
name = "oarepo"
version = "12.2.12"
description = "CESNET, UCT Prague and NTK wrapper around Invenio v3."
keywords = [ "oarepo",
     "invenio",
    ]
readme = "README.md"
classifiers = [ "Development Status :: 3 - Alpha",
     "Environment :: Web Environment",
     "Intended Audience :: Developers",
     "License :: OSI Approved :: MIT License",
     "Operating System :: OS Independent",
     "Programming Language :: Python",
     "Programming Language :: Python :: 3",
     "Programming Language :: Python :: 3.7",
     "Programming Language :: Python :: 3.8",
     "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
     "Topic :: Software Development :: Libraries :: Python Modules",
    ]
requires-python = ">=3.10"
dependencies = [ "aiobotocore==2.22.0",
     "aiohappyeyeballs==2.6.1",
     "aiohttp==3.11.18",
     "aioitertools==0.12.0",
     "aiosignal==1.3.2",
     "alabaster==0.7.16",
     "alembic==1.10.4",
     "amqp==5.3.1",
     "aniso8601==10.0.1",
     "appdirs==1.4.4",
     "arrow==1.3.0",
     "asttokens==3.0.0",
     "attrs==25.3.0",
     "babel==2.17.0",
     "babel-edtf==1.2.1",
     "base32-lib==1.0.2",
     "beautifulsoup4==4.13.4",
     "bibtexparser==1.4.3",
     "billiard==4.2.1",
     "bleach==6.2.0",
     "blinker==1.9.0",
     "boto3==1.37.3",
     "botocore==1.37.3",
     "build==1.2.2.post1",
     "cachelib==0.13.0",
     "cairocffi==1.7.1",
     "cairosvg==2.7.1",
     "celery==5.3.6",
     "certifi==2025.4.26",
     "cffi==1.17.1",
     "charset-normalizer==3.4.2",
     "check-manifest==0.50",
     "citeproc-py==0.6.0",
     "citeproc-py-styles==0.1.3",
     "click==8.1.8",
     "click-default-group==1.2.4",
     "click-didyoumean==0.3.1",
     "click-plugins==1.1.1",
     "click-repl==0.3.0",
     "commonmark==0.9.1",
     "commonmeta-py==0.8.6",
     "counter-robots==2025.2",
     "coverage==7.8.0",
     "cryptography==44.0.3",
     "cssselect2==0.8.0",
     "datacite==1.2.0",
     "dateparser==1.2.0",
     "dcxml==0.1.2",
     "decorator==5.2.1",
     "defusedxml==0.7.1",
     "deprecated==1.2.18",
     "dictdiffer==0.9.0",
     "dnspython==2.7.0",
     "docker-services-cli==0.12.0",
     "docutils==0.19",
     "dojson==1.5.0",
     "edtf==5.0.0",
     "email-validator==2.2.0",
     "events==0.5",
     "executing==2.2.0",
     "faker==37.1.0",
     "fastjsonschema==2.21.1",
     "flask==2.2.5",
     "flask-admin==1.6.1",
     "flask-alembic==2.0.1",
     "flask-babel==4.0.0",
     "flask-caching==2.3.1",
     "flask-celeryext==0.5.0",
     "flask-collect-invenio==1.4.0",
     "flask-cors==5.0.1",
     "flask-iiif==1.2.0",
     "flask-kvsession-invenio==0.6.4",
     "flask-limiter==2.9.2",
     "flask-login==0.6.3",
     "flask-mail==0.9.1",
     "flask-menu==2.0.0",
     "flask-oauthlib==0.9.6",
     "flask-principal==0.4.0",
     "flask-resources==1.2.0",
     "flask-restful==0.3.10",
     "flask-security-invenio==3.4.0",
     "flask-shell-ipython==0.5.3",
     "flask-sqlalchemy==2.5.1",
     "flask-talisman==0.8.1",
     "flask-webpackext==2.1.0",
     "flask-wtf==1.2.2",
     "frozenlist==1.6.0",
     "fs==2.4.16",
     "fsspec==2025.3.2",
     "ftfy==4.4.3",
     "future==1.0.0",
     "geojson==3.2.0",
     "ghp-import==2.1.0",
     "github3-py==4.0.1",
     "greenlet==3.2.1",
     "html5lib==1.1",
     "humanize==4.12.3",
     "idna==3.10",
     "idutils==1.4.2",
     "imagesize==1.4.1",
     "importlib-metadata==7.2.1",
     "importlib-resources==6.5.2",
     "infinity==1.5",
     "iniconfig==2.1.0",
     "intervals==0.9.2",
     "invenio-access==2.1.0",
     "invenio-accounts==5.2.0",
     "invenio-admin==1.4.1",
     "invenio-administration==2.2.4.post1002",
     "invenio-app==1.5.1",
     "invenio-assets==3.2.0",
     "invenio-banners==3.3.1.post1000",
     "invenio-base==1.4.0",
     "invenio-cache==1.3.1",
     "invenio-celery==1.3.2",
     "invenio-communities==13.1.1.post1000",
     "invenio-config==1.0.4",
     "invenio-db==1.3.1",
     "invenio-drafts-resources==3.3.0.post1000",
     "invenio-files-rest==2.3.0",
     "invenio-formatter==2.0.4",
     "invenio-github==1.5.2",
     "invenio-i18n==2.2.0",
     "invenio-indexer==2.4.0",
     "invenio-jsonschemas==1.1.5",
     "invenio-logging==2.1.5",
     "invenio-mail==2.3.0",
     "invenio-notifications==0.6.1",
     "invenio-oaiserver==2.4.0.post1000",
     "invenio-oauth2server==2.5.0",
     "invenio-oauthclient==4.2.0.post1000",
     "invenio-pages==4.1.2",
     "invenio-pidstore==1.3.5",
     "invenio-previewer==2.2.2",
     "invenio-queues==1.0.1",
     "invenio-records==2.4.1",
     "invenio-records-files==1.2.1",
     "invenio-records-permissions==0.21.0",
     "invenio-records-resources==5.11.1.post1001",
     "invenio-records-rest==2.4.1",
     "invenio-records-ui==1.3.0",
     "invenio-requests==4.1.3.post1000",
     "invenio-rest==1.5.1",
     "invenio-s3==1.0.7.post1000",
     "invenio-search==2.4.1",
     "invenio-search-ui==2.8.10",
     "invenio-stats==4.4.0",
     "invenio-theme==3.6.1",
     "invenio-userprofiles==3.1.0",
     "invenio-users-resources==5.2.1",
     "invenio-vocabularies==3.5.0",
     "invenio-webhooks==1.0.1",
     "ipython==9.2.0",
     "ipython-pygments-lexers==1.1.1",
     "isbnlib==3.10.14",
     "isort==6.0.1",
     "itsdangerous==2.0.1",
     "jedi==0.19.2",
     "jinja2==3.1.6",
     "jmespath==1.0.1",
     "jsmin==3.0.1",
     "jsonpatch==1.33",
     "jsonpointer==3.0.0",
     "jsonref==1.1.0",
     "jsonresolver==0.4.0",
     "jsonschema==4.23.0",
     "jsonschema-specifications==2025.4.1",
     "jupyter-client==8.6.3",
     "jupyter-core==5.7.2",
     "jupyterlab-pygments==0.3.0",
     "kombu==5.5.3",
     "limits==5.1.0",
     "luqum==1.0.0",
     "lxml==5.4.0",
     "lxml-html-clean==0.4.2",
     "mako==1.3.10",
     "markdown==3.8",
     "markupsafe==3.0.2",
     "marshmallow==3.26.1",
     "marshmallow-oneofschema==3.1.1",
     "marshmallow-utils==0.12.0",
     "matplotlib-inline==0.1.7",
     "maxminddb==2.7.0",
     "maxminddb-geolite2==2018.703",
     "mergedeep==1.3.4",
     "mistune==3.1.3",
     "mkdocs==1.6.1",
     "mkdocs-get-deps==0.2.0",
     "mkdocs-jupyter==0.12.0",
     "mkdocs-material==8.5.11",
     "mkdocs-material-extensions==1.3.1",
     "msgpack==1.1.0",
     "multidict==6.4.3",
     "nameparser==1.1.3",
     "nbclient==0.10.2",
     "nbconvert==7.16.6",
     "nbformat==5.10.4",
     "nbstripout==0.6.2",
     "oauthlib==2.1.0",
     "opensearch-dsl==2.1.0",
     "opensearch-py==2.8.0",
     "ordered-set==4.1.0",
     "packaging==25.0",
     "pandocfilters==1.5.1",
     "parso==0.8.4",
     "passlib==1.7.4",
     "pathspec==0.12.1",
     "pexpect==4.9.0",
     "pillow==11.2.1",
     "platformdirs==4.3.7",
     "pluggy==1.5.0",
     "ply==3.11",
     "prompt-toolkit==3.0.51",
     "propcache==0.3.1",
     "psycopg2-binary==2.9.10",
     "ptyprocess==0.7.0",
     "pure-eval==0.2.3",
     "py==1.11.0",
     "pycodestyle==2.13.0",
     "pycountry==22.3.5",
     "pycparser==2.22",
     "pydash==6.0.2",
     "pydocstyle==6.3.0",
     "pygments==2.19.1",
     "pyjwt==2.10.1",
     "pymdown-extensions==10.15",
     "pymysql==1.1.1",
     "pynpm==0.3.0",
     "pyparsing==3.2.3",
     "pyproject-hooks==1.2.0",
     "pytest==7.1.3",
     "pytest-cov==6.1.1",
     "pytest-flask==1.3.0",
     "pytest-github-actions-annotate-failures==0.3.0",
     "pytest-invenio==2.2.1",
     "pytest-isort==4.0.0",
     "pytest-pycodestyle==2.4.1",
     "pytest-pydocstyle==2.4.0",
     "python-dateutil==2.9.0.post0",
     "python-geoip==1.2",
     "python-slugify==8.0.4",
     "pytz==2024.1",
     "pywebpack==2.1.0",
     "pyyaml==6.0.2",
     "pyyaml-env-tag==0.1",
     "pyzmq==26.4.0",
     "redis==6.0.0",
     "referencing==0.36.2",
     "regex==2024.11.6",
     "requests==2.32.3",
     "requests-oauthlib==1.1.0",
     "rich==12.6.0",
     "rpds-py==0.24.0",
     "s3fs==0.4.2",
     "s3transfer==0.11.3",
     "selenium==3.141.0",
     "setuptools==80.3.1",
     "simplejson==3.20.1",
     "simplekv==0.14.1",
     "six==1.17.0",
     "snowballstemmer==2.2.0",
     "soupsieve==2.7",
     "speaklater==1.3",
     "sphinx==7.3.7",
     "sphinx-autodoc-typehints==1.25.3",
     "sphinxcontrib-applehelp==2.0.0",
     "sphinxcontrib-devhelp==2.0.0",
     "sphinxcontrib-htmlhelp==2.1.0",
     "sphinxcontrib-issuetracker==0.11",
     "sphinxcontrib-jsmath==1.0.1",
     "sphinxcontrib-qthelp==2.0.0",
     "sphinxcontrib-serializinghtml==2.0.0",
     "sqlalchemy==1.4.54",
     "sqlalchemy-continuum==1.4.1",
     "sqlalchemy-utils==0.38.3",
     "stack-data==0.6.3",
     "text-unidecode==1.3",
     "tinycss2==1.4.0",
     "tomli==2.2.1",
     "tornado==6.4.2",
     "tqdm==4.67.1",
     "traitlets==5.14.3",
     "types-beautifulsoup4==4.12.0.20250204",
     "types-bleach==6.2.0.20241123",
     "types-dateparser==1.2.0.20250408",
     "types-html5lib==1.1.11.20241018",
     "types-python-dateutil==2.9.0.20241206",
     "types-pyyaml==6.0.12.20250402",
     "types-requests==2.31.0.6",
     "types-urllib3==1.26.25.14",
     "types-xmltodict==0.13.0.3",
     "typing-extensions==4.13.2",
     "tzdata==2025.2",
     "tzlocal==5.3.1",
     "ua-parser==1.0.1",
     "ua-parser-builtins==0.18.0.post1",
     "uritemplate==4.1.1",
     "uritools==5.0.0",
     "urllib3==2.4.0",
     "validators==0.35.0",
     "vine==5.1.0",
     "wand==0.6.13",
     "watchdog==2.2.1",
     "wcwidth==0.2.13",
     "webargs==5.5.3",
     "webencodings==0.5.1",
     "werkzeug==2.2.3",
     "wrapt==1.17.2",
     "wtforms==3.1.2",
     "wtforms-alchemy==0.18.0",
     "wtforms-components==0.11.0",
     "xmltodict==0.12.0",
     "yarl==1.20.0",
     "zipp==3.21.0",
     "zipstream-ng==1.8.0",
    ]
[[project.authors]]
name = "UCT Prague, CESNET z.s.p.o., NTK"
email = "miroslav.simek@cesnet.cz"

[build-system]
requires = [ "setuptools",
     "setuptools-scm",
    ]
build-backend = "setuptools.build_meta"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/oarepo/oarepo"

[project.optional-dependencies]
rdm = [ "invenio-app-rdm==12.1.0.post1000",
     "invenio-rdm-records==10.9.2.post1000",
    ]
test = []
tests = []
dev = []
devs = []
s3 = []

[project.entry-points."invenio_assets.webpack"]
oarepo = "oarepo.webpack:theme"

[tool.setuptools.package-data]
oarepo = [ "oarepo/assets/semantic-ui/*",
    ]
