[project]
name = "oarepo"
version = "14.0.2"
description = "CESNET, UCT Prague and NTK wrapper around Invenio v3."
keywords = [ "oarepo",
     "invenio",
    ]
readme = "README.md"
classifiers = [ "Development Status :: 3 - Alpha",
     "Environment :: Web Environment",
     "Intended Audience :: Developers",
     "License :: OSI Approved :: MIT License",
     "Operating System :: OS Independent",
     "Programming Language :: Python",
     "Programming Language :: Python :: 3",
     "Programming Language :: Python :: 3.7",
     "Programming Language :: Python :: 3.8",
     "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
     "Topic :: Software Development :: Libraries :: Python Modules",
    ]
requires-python = ">=3.13,<3.14"
dependencies = [ "aiobotocore==2.24.2",
     "aiohappyeyeballs==2.6.1",
     "aiohttp==3.12.15",
     "aioitertools==0.12.0",
     "aiosignal==1.4.0",
     "alabaster==1.0.0",
     "alembic==1.16.5",
     "amqp==5.3.1",
     "aniso8601==10.0.1",
     "appdirs==1.4.4",
     "arrow==1.3.0",
     "asttokens==3.0.0",
     "attrs==25.3.0",
     "babel==2.17.0",
     "babel-edtf==1.2.1",
     "base32-lib==1.0.2",
     "beautifulsoup4==4.13.5",
     "bibtexparser==1.4.3",
     "billiard==4.2.2",
     "black==25.9.0",
     "bleach==6.2.0",
     "blinker==1.9.0",
     "botocore==1.40.18",
     "build==1.3.0",
     "cachelib==0.13.0",
     "cairocffi==1.7.1",
     "cairosvg==2.8.2",
     "celery==5.4.0",
     "certifi==2025.8.3",
     "cffi==2.0.0",
     "charset-normalizer==3.4.3",
     "check-manifest==0.50",
     "citeproc-py==0.9.0",
     "citeproc-py-styles==0.1.5.528422",
     "click==8.3.0",
     "click-default-group==1.2.4",
     "click-didyoumean==0.3.1",
     "click-plugins==1.1.1.2",
     "click-repl==0.3.0",
     "commonmark==0.9.1",
     "commonmeta-py==0.170",
     "counter-robots==2025.2",
     "coverage==7.10.7",
     "cryptography==46.0.1",
     "cssselect2==0.8.0",
     "datacite==1.3.1",
     "dateparser==1.2.0",
     "dcxml==0.1.2",
     "decorator==5.2.1",
     "defusedxml==0.7.1",
     "deprecated==1.2.18",
     "dictdiffer==0.9.0",
     "dnspython==2.8.0",
     "docker-services-cli==0.12.0",
     "docutils==0.21.2",
     "dojson==1.7.0",
     "edtf==5.0.0",
     "elementpath==5.0.4",
     "email-validator==2.3.0",
     "events==0.5",
     "executing==2.2.1",
     "faker==37.8.0",
     "fancycompleter==0.11.1",
     "fastjsonschema==2.21.2",
     "flask==3.1.2",
     "flask-alembic==3.1.1",
     "flask-babel==4.0.0",
     "flask-caching==2.3.1",
     "flask-celeryext==0.5.0",
     "flask-collect-invenio==1.4.0",
     "flask-cors==6.0.1",
     "flask-iiif==1.2.1",
     "flask-kvsession-invenio==0.6.4",
     "flask-limiter==2.9.2",
     "flask-login==0.6.3",
     "flask-mail==0.9.1",
     "flask-menu==2.0.0",
     "flask-oauthlib-invenio==1.1.2",
     "flask-principal==0.4.0",
     "flask-resources==1.2.0",
     "flask-restful==0.3.10",
     "flask-security-invenio==3.7.0",
     "flask-shell-ipython==0.5.3",
     "flask-sqlalchemy==3.1.1",
     "flask-talisman==0.8.1",
     "flask-webpackext==2.1.0",
     "flask-wtf==1.2.2",
     "frozenlist==1.7.0",
     "fs==2.4.16",
     "fsspec==2025.9.0",
     "ftfy==6.3.1",
     "furl==2.1.4",
     "future==1.0.0",
     "geojson==3.2.0",
     "github3-py==4.0.1",
     "greenlet==3.2.4",
     "h11==0.16.0",
     "humanize==4.13.0",
     "idna==3.10",
     "idutils==1.5.0",
     "imagesize==1.4.1",
     "importlib-metadata==8.7.0",
     "importlib-resources==6.5.2",
     "infinity==1.5",
     "iniconfig==2.1.0",
     "intervals==0.9.2",
     "invenio-access==4.2.0",
     "invenio-accounts==6.2.0",
     "invenio-administration==4.3.0.744285",
     "invenio-app==2.3.0",
     "invenio-assets==4.2.0",
     "invenio-audit-logs==0.3.2",
     "invenio-banners==5.2.0",
     "invenio-base==2.3.2",
     "invenio-cache==2.1.0",
     "invenio-celery==2.2.0",
     "invenio-checks==2.0.0",
     "invenio-collections==2.0.0",
     "invenio-communities==21.0.0.986137",
     "invenio-config==1.1.0",
     "invenio-db==2.1.1",
     "invenio-drafts-resources==7.2.0.284413",
     "invenio-files-rest==3.3.1",
     "invenio-formatter==3.3.0",
     "invenio-github==3.0.1",
     "invenio-i18n==3.4.2",
     "invenio-indexer==3.1.0",
     "invenio-jobs==5.0.0",
     "invenio-jsonschemas==2.1.0.108971",
     "invenio-logging==4.1.1",
     "invenio-mail==2.3.0",
     "invenio-notifications==1.2.1",
     "invenio-oaiserver==3.7.2.662139",
     "invenio-oauth2server==3.3.0",
     "invenio-oauthclient==5.3.0.445008",
     "invenio-pages==7.2.0",
     "invenio-pidstore==2.2.0",
     "invenio-previewer==3.3.0",
     "invenio-queues==1.0.1",
     "invenio-records==3.1.0",
     "invenio-records-files==1.2.1",
     "invenio-records-permissions==1.2.0",
     "invenio-records-resources==8.6.0.785321",
     "invenio-records-rest==3.2.0",
     "invenio-records-ui==2.1.0",
     "invenio-requests==10.0.1.621211",
     "invenio-rest==2.0.5",
     "invenio-s3==3.0.2",
     "invenio-search==3.1.0.62748",
     "invenio-search-ui==4.1.2",
     "invenio-sitemap==0.3.0",
     "invenio-stats==5.1.1",
     "invenio-theme==4.4.1",
     "invenio-userprofiles==4.1.0",
     "invenio-users-resources==9.0.1",
     "invenio-vocabularies==9.0.0.274881",
     "invenio-webhooks==1.1.0",
     "ipython==9.5.0",
     "ipython-pygments-lexers==1.1.1",
     "isal==1.8.0",
     "isbnlib==3.10.14",
     "isort==6.0.1",
     "itsdangerous==2.2.0",
     "jedi==0.19.2",
     "jinja2==3.1.6",
     "jmespath==1.0.1",
     "jsmin==3.0.1",
     "jsonpatch==1.33",
     "jsonpointer==3.0.0",
     "jsonref==1.1.0",
     "jsonresolver==0.4.1",
     "jsonschema==4.25.1",
     "jsonschema-specifications==2025.9.1",
     "jupyter-client==8.6.3",
     "jupyter-core==5.8.1",
     "jupyterlab-pygments==0.3.0",
     "kombu==5.5.4",
     "limits==5.5.0",
     "luqum==1.0.0",
     "lxml==6.0.2",
     "lxml-html-clean==0.4.2",
     "mako==1.3.10",
     "markupsafe==3.0.2",
     "marshmallow==3.26.1",
     "marshmallow-oneofschema==3.2.0",
     "marshmallow-utils==0.13.0",
     "matplotlib-inline==0.1.7",
     "maxminddb==2.8.2",
     "maxminddb-geolite2==2018.703",
     "mistune==3.1.4",
     "msgpack==1.1.1",
     "multidict==6.6.4",
     "mypy-extensions==1.1.0",
     "nameparser==1.1.3",
     "nbclient==0.10.2",
     "nbconvert==7.16.6",
     "nbformat==5.10.4",
     "nh3==0.2.22",
     "oauthlib==3.3.1",
     "opensearch-dsl==2.1.0",
     "opensearch-py==2.8.0",
     "ordered-set==4.1.0",
     "orderedmultidict==1.0.1",
     "orjson==3.11.3",
     "orjsonl==1.0.0",
     "outcome==1.3.0.post0",
     "packaging==25.0",
     "pandocfilters==1.5.1",
     "parso==0.8.5",
     "passlib==1.7.4",
     "pathspec==0.12.1",
     "pdbpp==0.11.7",
     "pexpect==4.9.0",
     "pikepdf==9.11.0",
     "pillow==11.3.0",
     "pip==25.2",
     "platformdirs==4.4.0",
     "pluggy==1.6.0",
     "ply==3.11",
     "polib==1.2.0",
     "prompt-toolkit==3.0.52",
     "propcache==0.3.2",
     "psycopg2-binary==2.9.10",
     "ptyprocess==0.7.0",
     "pure-eval==0.2.3",
     "pycodestyle==2.14.0",
     "pycountry==24.6.1",
     "pycparser==2.23",
     "pydash==6.0.2",
     "pydocstyle==6.3.0",
     "pygments==2.19.2",
     "pyjwt==2.10.1",
     "pymysql==1.1.2",
     "pynpm==0.3.0",
     "pyparsing==3.2.5",
     "pyproject-hooks==1.2.0",
     "pysocks==1.7.1",
     "pytest==8.4.2",
     "pytest-black-ng==0.4.1",
     "pytest-cov==7.0.0",
     "pytest-flask==1.3.0",
     "pytest-github-actions-annotate-failures==0.3.0",
     "pytest-invenio==3.4.2",
     "pytest-isort==4.0.0",
     "pytest-pycodestyle==2.5.0",
     "pytest-pydocstyle==2.4.0",
     "python-dateutil==2.9.0.post0",
     "python-geoip==1.2",
     "python-slugify==8.0.4",
     "pytokens==0.1.10",
     "pytz==2024.1",
     "pywebpack==2.2.0",
     "pyyaml==6.0.2",
     "pyzmq==27.1.0",
     "rdflib==7.2.1",
     "redis==6.4.0",
     "referencing==0.36.2",
     "regex==2025.9.18",
     "requests==2.32.5",
     "requests-oauthlib==2.0.0",
     "requests-toolbelt==1.0.0",
     "rich==12.6.0",
     "roman-numerals-py==3.1.0",
     "rpds-py==0.27.1",
     "s3fs==2025.9.0",
     "selenium==4.35.0",
     "setuptools==80.9.0",
     "simplejson==3.20.1",
     "simplekv==0.14.1",
     "six==1.17.0",
     "sniffio==1.3.1",
     "snowballstemmer==2.2.0",
     "sortedcontainers==2.4.0",
     "soupsieve==2.8",
     "sparqlwrapper==2.0.0",
     "speaklater==1.3",
     "sphinx==8.2.3",
     "sphinxcontrib-applehelp==2.0.0",
     "sphinxcontrib-devhelp==2.0.0",
     "sphinxcontrib-htmlhelp==2.1.0",
     "sphinxcontrib-jsmath==1.0.1",
     "sphinxcontrib-qthelp==2.0.0",
     "sphinxcontrib-serializinghtml==2.0.0",
     "sqlalchemy==2.0.43",
     "sqlalchemy-continuum==1.4.2",
     "sqlalchemy-utils==0.41.2",
     "stack-data==0.6.3",
     "text-unidecode==1.3",
     "time-machine==2.19.0",
     "tinycss2==1.4.0",
     "toml==0.10.2",
     "tornado==6.5.2",
     "traitlets==5.14.3",
     "trio==0.30.0",
     "trio-websocket==0.12.2",
     "types-beautifulsoup4==4.12.0.20250516",
     "types-dateparser==1.2.2.20250809",
     "types-html5lib==1.1.11.20250917",
     "types-python-dateutil==2.9.0.20250822",
     "types-pyyaml==6.0.12.20250915",
     "types-xmltodict==0.15.0.20250907",
     "typing-extensions==4.14.1",
     "tzdata==2025.2",
     "tzlocal==5.3.1",
     "ua-parser==1.0.1",
     "ua-parser-builtins==0.18.0.post1",
     "uritemplate==4.2.0",
     "uritools==5.0.0",
     "urllib3==2.5.0",
     "validators==0.35.0",
     "vine==5.1.0",
     "wand==0.6.13",
     "watchdog==6.0.0",
     "wcwidth==0.2.14",
     "webargs==5.5.3",
     "webencodings==0.5.1",
     "websocket-client==1.8.0",
     "werkzeug==3.1.3",
     "wrapt==1.17.3",
     "wsproto==1.2.0",
     "wtforms==3.2.1",
     "wtforms-alchemy==0.19.1",
     "wtforms-components==0.11.0",
     "xmlschema==4.1.0",
     "xmltodict==0.12.0",
     "xopen==2.0.2",
     "yarl==1.20.1",
     "zipp==3.23.0",
     "zipstream-ng==1.9.0",
     "zlib-ng==1.0.0",
     "python-dotenv>=1.1.1,<2",
     "marshmallow-i18n-messages>=0.1.0,<1.0.0",
    ]
[[project.authors]]
name = "UCT Prague, CESNET z.s.p.o., NTK"
email = "miroslav.simek@cesnet.cz"

[build-system]
requires = [ "setuptools",
     "setuptools-scm",
    ]
build-backend = "setuptools.build_meta"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/oarepo/oarepo"

[project.optional-dependencies]
rdm = [ "invenio-app-rdm==14.0.0.402518b1.dev1",
     "invenio-rdm-records==21.0.0.601062",
    ]
test = [ "pytest-invenio",
    ]
tests = [ "pytest-invenio",
    ]
dev = [ "pytest-invenio",
    ]
devs = [ "pytest-invenio",
    ]
s3 = []

[project.entry-points."invenio_assets.webpack"]
oarepo = "oarepo.webpack:theme"

[project.entry-points."invenio_config.module"]
oarepo = "oarepo.config.initial_configuration"

[tool.setuptools.package-data]
oarepo = [ "oarepo/assets/semantic-ui/*",
     "oarepo/collected_translations/*",
    ]
